"""add documentation

Revision ID: 50492ef78772
Revises: 82d771931bf4
Create Date: 2024-06-20 19:04:12.160501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50492ef78772'
down_revision: Union[str, None] = '82d771931bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('documentation', sa.String(length=255), server_default='No documentation', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'documentation')
    # ### end Alembic commands ###
