"""add cur amp

Revision ID: b619faf31bd3
Revises: 1ab6795c8b63
Create Date: 2024-06-21 21:41:24.984398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b619faf31bd3'
down_revision: Union[str, None] = '1ab6795c8b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('current_amperage', sa.Integer(), server_default='-1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'current_amperage')
    # ### end Alembic commands ###
